QUnit.testSuites([
    { name: "expressions Test Suite", path: "./expressions.html" },
    { name: "statements Test Suite", path: "./statements.html" },
    { name: "omit-tag tag Test Suite", path: "./omit-tag.html" },
    { name: "vars scope Test Suite", path: "./scope.html" },
	{ name: "loops Test Suite", path: "./loops.html" },
	{ name: "nested loops Test Suite", path: "./nestedLoops.html" },
	{ name: "macros Test Suite", path: "./macros.html" },
    { name: "external sync macros Test Suite", path: "./externalSyncMacros-calls.html" },
    { name: "jquery expressions Test Suite", path: "./jquery.html" },
	{ name: "on-error tag Test Suite", path: "./on-error.html" },
    { name: "jquery plugin Test Suite", path: "./jqueryPlugin.html" },
    { name: "formatters Test Suite", path: "./format.html" },
    { name: "rerun simple Test Suite", path: "./rerunSimple.html" },
    { name: "rerun sync simple Test Suite", path: "./rerunSyncSimple.html" },
    { name: "rerun macro Test Suite", path: "./rerunMacros.html" },
    { name: "i18n Test Suite", path: "./i18n.html" },
    //{ name: "i18n async Test Suite", path: "./i18nAsync.html" },
    { name: "custom expressions Test Suite", path: "./customExpressions.html" },
    { name: "errors Test Suite", path: "./errors.html" },
    { name: "multiroot Test Suite", path: "./multiroot.html" },
    { name: "original tags Test Suite", path: "./original.html" },
]);
